Repository DeepDive-2nd-Project-Reviewers/server, pull requests merged in 2025-01, with the labels that each got.

#5 [Feat] review 초기 클래스 생성
  src/main/java/reviewers/server/domain/review/controller/ReviewController.java
  src/main/java/reviewers/server/domain/review/entity/Review.java
  src/main/java/reviewers/server/domain/review/repository/ReviewInterface.java
  src/main/java/reviewers/server/domain/review/service/ReviewService.java
  src/main/resources/application.yml
Labels: feat

#8 Feat: User Entity 구현
  src/main/java/reviewers/server/domain/user/entity/User.java
Labels: feat

#9 [Feat] Comment 도메인 초기 세팅
  src/main/java/reviewers/server/domain/comment/controller/CommentController.java
  src/main/java/reviewers/server/domain/comment/entity/Comment.java
  src/main/java/reviewers/server/domain/comment/repository/CommentRepository.java
  src/main/java/reviewers/server/domain/comment/service/CommentService.java
Labels: feat

#6 [Feat] contents 초기구현 (#1)
  src/main/java/reviewers/server/domain/contents/controller/ContentsController.java
  src/main/java/reviewers/server/domain/contents/dto/ContentsRequestDto.java
  src/main/java/reviewers/server/domain/contents/dto/ContentsResponseDto.java
  src/main/java/reviewers/server/domain/contents/entity/Actor.java
  src/main/java/reviewers/server/domain/contents/entity/ActorAppearances.java
  src/main/java/reviewers/server/domain/contents/entity/ContentHeart.java
  src/main/java/reviewers/server/domain/contents/entity/Contents.java
  src/main/java/reviewers/server/domain/contents/mapper/ContentsMapper.java
  src/main/java/reviewers/server/domain/contents/repository/ActorAppearancesRepository.java
  src/main/java/reviewers/server/domain/contents/repository/ActorRepository.java
  src/main/java/reviewers/server/domain/contents/repository/ContentHeartRepository.java
  src/main/java/reviewers/server/domain/contents/repository/ContentsRepository.java
  src/main/java/reviewers/server/domain/contents/service/ActorService.java
  src/main/java/reviewers/server/domain/contents/service/ContentsService.java
Labels: feat

#13 [Feat] api 반환 커스터마이징하기
  src/main/java/reviewers/server/domain/contents/service/ContentsService.java
  src/main/java/reviewers/server/global/common/BaseEntity.java
  src/main/java/reviewers/server/global/exception/BaseErrorException.java
  src/main/java/reviewers/server/global/exception/ErrorType.java
  src/main/java/reviewers/server/global/exception/ExceptionResponse.java
  src/main/java/reviewers/server/global/exception/GlobalExceptionHandler.java
  src/main/java/reviewers/server/global/success/SuccessResponse.java
  src/main/java/reviewers/server/global/success/SuccessResponseStatus.java
Labels: feat

#15 [Feat] SecurityConfig 초기구현, Jwt Provider, Filter 구현
  src/main/java/reviewers/server/domain/config/WebSecurityConfig.java
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/domain/user/provider/JwtProvider.java
Labels: feat

#19 Feat/#18/의존성 추가 jwt 필터 provider 기능 추가
  build.gradle
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/domain/user/provider/JwtProvider.java
Labels: feat

#20 [Feat] content 응답 수정
  src/main/java/reviewers/server/domain/contents/controller/ContentsController.java
Labels: feat

#21 [Feat] User Domain Dto, Repository, Controller 구현
  src/main/java/reviewers/server/domain/user/controller/UserController.java
  src/main/java/reviewers/server/domain/user/dto/request/LogoutRequestDto.java
  src/main/java/reviewers/server/domain/user/dto/request/RefreshAccessTokenRequestDto.java
  src/main/java/reviewers/server/domain/user/dto/request/SignInRequestDto.java
  src/main/java/reviewers/server/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/reviewers/server/domain/user/dto/response/LogoutResponseDto.java
  src/main/java/reviewers/server/domain/user/dto/response/RefreshAccessTokenResponseDto.java
  src/main/java/reviewers/server/domain/user/dto/response/SignInResponseDto.java
  src/main/java/reviewers/server/domain/user/dto/response/SignUpResponseDto.java
  src/main/java/reviewers/server/domain/user/repository/UserRepository.java
Labels: feat

#25 [Feat, fix] userservice 구현, jwt secret 키 추가
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/domain/user/provider/JwtProvider.java
  src/main/java/reviewers/server/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: fix, feat

#26 [Feat] content 전체 조회 수정
  src/main/java/reviewers/server/domain/contents/controller/ContentsController.java
  src/main/java/reviewers/server/domain/contents/repository/ContentsRepository.java
  src/main/java/reviewers/server/domain/contents/service/ContentsService.java
Labels: feat

#27 [Feat] contents 페이징처리
  src/main/java/reviewers/server/domain/contents/controller/ContentsController.java
  src/main/java/reviewers/server/domain/contents/repository/ContentsRepository.java
  src/main/java/reviewers/server/domain/contents/service/ContentsService.java
  src/main/java/reviewers/server/global/exception/ErrorType.java
Labels: feat

#28 Feat/#11/comment기능구현
  build.gradle
  src/main/java/reviewers/server/ServerApplication.java
  src/main/java/reviewers/server/domain/comment/controller/CommentController.java
  src/main/java/reviewers/server/domain/comment/dto/CommentRequestDto.java
  src/main/java/reviewers/server/domain/comment/dto/CommentResponseDto.java
  src/main/java/reviewers/server/domain/comment/dto/CommentUpdateRequestDto.java
  src/main/java/reviewers/server/domain/comment/entity/Comment.java
  src/main/java/reviewers/server/domain/comment/repository/CommentRepository.java
  src/main/java/reviewers/server/domain/comment/service/CommentConverter.java
  src/main/java/reviewers/server/domain/comment/service/CommentService.java
  src/main/java/reviewers/server/global/exception/ErrorType.java
Labels: feat

#33 [Feat] 도커 파일 추가
  Dockerfile
Labels: feat

#32 [Feat] emailservice, redisservice 구현
  build.gradle
  src/main/java/reviewers/server/domain/config/RedisConfig.java
  src/main/java/reviewers/server/domain/config/WebSecurityConfig.java
  src/main/java/reviewers/server/domain/user/controller/UserController.java
  src/main/java/reviewers/server/domain/user/dto/request/CheckCertificationRequestDto.java
  src/main/java/reviewers/server/domain/user/dto/request/EmailCertificationRequestDto.java
  src/main/java/reviewers/server/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/reviewers/server/domain/user/dto/response/LogoutResponseDto.java
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/domain/user/provider/EmailProvider.java
  src/main/java/reviewers/server/domain/user/repository/UserRepository.java
  src/main/java/reviewers/server/domain/user/service/EmailService.java
  src/main/java/reviewers/server/domain/user/service/RedisService.java
  src/main/java/reviewers/server/domain/user/service/UserService.java
  src/main/java/reviewers/server/global/exception/ErrorType.java
  src/main/resources/application.yml
Labels: feat

#35 [Feat] actor 구현
  src/main/java/reviewers/server/domain/contents/entity/Actor.java
  src/main/java/reviewers/server/domain/contents/entity/ActorAppearances.java
  src/main/java/reviewers/server/domain/contents/mapper/ContentsMapper.java
  src/main/java/reviewers/server/domain/contents/repository/ActorAppearancesRepository.java
  src/main/java/reviewers/server/domain/contents/repository/ActorRepository.java
  src/main/java/reviewers/server/domain/contents/service/ActorAppearancesService.java
  src/main/java/reviewers/server/domain/contents/service/ActorService.java
  src/main/java/reviewers/server/domain/contents/service/ContentsService.java
Labels: feat

#39 [Feat] 포트 명시
  src/main/resources/application.yml
Labels: feat

#44 [Feat] Google OAuth 로그인 기능 구현
  .gitignore
  build.gradle
  src/main/java/reviewers/server/domain/oauth/controller/ViewController.java
  src/main/java/reviewers/server/domain/oauth/dto/CustomOAuth2User.java
  src/main/java/reviewers/server/domain/oauth/dto/GoogleResponse.java
  src/main/java/reviewers/server/domain/oauth/dto/OAuth2Response.java
  src/main/java/reviewers/server/domain/oauth/service/OAuth2UserCustomService.java
  src/main/java/reviewers/server/domain/user/entity/User.java
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/domain/user/repository/UserRepository.java
  src/main/java/reviewers/server/domain/user/service/UserService.java
  src/main/java/reviewers/server/global/config/WebSecurityConfig.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: feat

#46 [Feat] securityconfig 예외처리 jwt filter 예외처리 userentity 연관관계 매핑
  src/main/java/reviewers/server/domain/user/controller/UserController.java
  src/main/java/reviewers/server/domain/user/entity/User.java
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/global/config/WebSecurityConfig.java
  src/main/java/reviewers/server/global/exception/ErrorType.java
Labels: feat

#49 [Feat] s3를 이용한 이미지 업로드 구현
  build.gradle
  src/main/java/reviewers/server/domain/contents/controller/ContentsController.java
  src/main/java/reviewers/server/domain/contents/dto/ContentsRequestDto.java
  src/main/java/reviewers/server/domain/contents/dto/ContentsResponseDto.java
  src/main/java/reviewers/server/domain/contents/entity/Contents.java
  src/main/java/reviewers/server/domain/contents/mapper/ContentsMapper.java
  src/main/java/reviewers/server/domain/contents/service/ContentsService.java
  src/main/java/reviewers/server/domain/contents/service/FileUploadService.java
  src/main/java/reviewers/server/global/common/BaseEntity.java
  src/main/java/reviewers/server/global/config/S3Config.java
  src/main/java/reviewers/server/global/exception/ErrorType.java
  src/main/resources/application.yml
Labels: feat

#51 [Feat] review 서비스 구현
  build.gradle
  src/main/java/reviewers/server/domain/comment/service/CommentService.java
  src/main/java/reviewers/server/domain/contents/entity/Contents.java
  src/main/java/reviewers/server/domain/heart/review/service/ReviewHeartService.java
  src/main/java/reviewers/server/domain/oauth/service/OAuth2UserCustomService.java
  src/main/java/reviewers/server/domain/review/controller/ReviewController.java
  src/main/java/reviewers/server/domain/review/dto/ReviewDetailResponseDto.java
  src/main/java/reviewers/server/domain/review/dto/ReviewRequestDto.java
  src/main/java/reviewers/server/domain/review/dto/ReviewResponseDto.java
  src/main/java/reviewers/server/domain/review/entity/Review.java
  src/main/java/reviewers/server/domain/review/repository/ReviewInterface.java
  src/main/java/reviewers/server/domain/review/repository/ReviewRepository.java
  src/main/java/reviewers/server/domain/review/service/ReviewService.java
  src/main/java/reviewers/server/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/reviewers/server/domain/user/entity/Role.java
  src/main/java/reviewers/server/domain/user/entity/User.java
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/domain/user/service/UserService.java
  src/main/java/reviewers/server/global/config/SwaggerConfig.java
  src/main/java/reviewers/server/global/config/WebSecurityConfig.java
  src/main/java/reviewers/server/global/exception/ErrorType.java
  src/main/java/reviewers/server/global/util/SecurityUtil.java
Labels: fix, feat

#55 [Feat] 토큰 값에 userid 추가 review 생성 시 토큰에서 userid 값 추출
  src/main/java/reviewers/server/domain/review/entity/Review.java
  src/main/java/reviewers/server/domain/review/service/ReviewService.java
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/domain/user/provider/JwtProvider.java
  src/main/java/reviewers/server/domain/user/service/UserService.java
  src/main/java/reviewers/server/global/exception/ErrorType.java
Labels: feat

#53 [Refactor] RESTful 규칙에 맞게 API 수정
  src/main/java/reviewers/server/domain/comment/controller/CommentController.java
  src/main/java/reviewers/server/domain/contents/controller/ContentsController.java
  src/main/java/reviewers/server/domain/contents/dto/ContentsRequestDto.java
  src/main/java/reviewers/server/domain/contents/dto/ContentsResponseDto.java
  src/main/java/reviewers/server/domain/contents/entity/Category.java
  src/main/java/reviewers/server/domain/contents/entity/Contents.java
  src/main/java/reviewers/server/domain/contents/repository/ContentsRepository.java
  src/main/java/reviewers/server/domain/contents/service/ContentsService.java
  src/main/java/reviewers/server/domain/review/controller/ReviewController.java
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/global/config/WebSecurityConfig.java
Labels: refactor

#62 [Fix] publicUrl 수정
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
Labels: fix

#60 [Fix] Google OAuth AccessToken 인가
  src/main/java/reviewers/server/domain/oauth/Filter/GoogleTokenVerifier.java
  src/main/java/reviewers/server/domain/oauth/controller/ViewController.java
  src/main/java/reviewers/server/domain/oauth/dto/CustomOAuth2User.java
  src/main/java/reviewers/server/domain/oauth/dto/GoogleResponse.java
  src/main/java/reviewers/server/domain/oauth/dto/OAuth2Response.java
  src/main/java/reviewers/server/domain/oauth/service/OAuth2UserCustomService.java
  src/main/java/reviewers/server/domain/user/entity/User.java
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/global/config/WebSecurityConfig.java
Labels: fix, feat

#63 [Fix] jwt토큰검사수정
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/global/config/WebSecurityConfig.java
Labels: fix

#64 [Fix] jwt토큰검사수정
  build.gradle
  src/main/resources/application.yml
Labels: feat

#65 fix: swagger 의존성 추가
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
Labels: fix

#68 [Fix] 토큰 검사 제외 경로 수정
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
Labels: fix

#71 [Feat] Google Authentication Filter 적용
  src/main/java/reviewers/server/domain/user/filter/JwtAuthenticationFilter.java
  src/main/java/reviewers/server/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: fix

#75 [Refactor] Review heartCount, starCount 타입 변경
  src/main/java/reviewers/server/domain/review/dto/ReviewDetailResponseDto.java
  src/main/java/reviewers/server/domain/review/dto/ReviewRequestDto.java
  src/main/java/reviewers/server/domain/review/entity/Review.java
  src/main/java/reviewers/server/domain/review/service/ReviewService.java
Labels: refactor

#80 [Test] userService 테스트 코드 작성
  src/main/java/reviewers/server/domain/user/dto/request/RefreshAccessTokenRequestDto.java
  src/test/java/reviewers/server/domain/user/service/UserServiceTest.java
Labels: test

#81 [Test] Contents 테스트 코드 작성
  build.gradle
  src/main/java/reviewers/server/ServerApplication.java
  src/main/java/reviewers/server/global/config/JpaAuditingConfiguration.java
  src/test/java/reviewers/server/domain/contents/repository/ContentsControllerTest.java
  src/test/java/reviewers/server/domain/contents/service/ContentsServiceTest.java
Labels: test

#83 [Feat] Review 테스트 코드 작성
  src/main/java/reviewers/server/domain/contents/entity/Contents.java
  src/test/java/reviewers/server/domain/review/service/ReviewServiceTest.java
Labels: fix, feat

#82 Update README.md
  README.md
Labels: feat

#93 [Fix] application.yml 수정
  src/main/resources/application.yml
Labels: fix

#94 [Feat] dockerfile 수정하기
  docker-compose.yml
  src/main/resources/application.yml
Labels: fix

#95 [Fix] yml 수정
  docker-compose.yml
Labels: hot fix

#96 [Fix] dockerfile 수정하기
  docker-compose.yml
Labels: fix

#97 [Fix] yml 수정
  src/main/resources/application.yml
Labels: fix
